In [1]:
print("hallo welt")

hallo welt


In [2]:
import keras
print(keras.__version__
    )

Using TensorFlow backend.


2.1.5


# Daten aus JSON 

hallo 


In [3]:
import urllib.request, json 
with urllib.request.urlopen("http://statistik.easycredit-bbl.de/XML/exchange/540/Schedule.php?type=json&saison=2017&fixedGamesOnly=0") as url:
    games = json.loads(url.read().decode())
    print(games)

{'timestamp': '1530965170', 'valid_from': '2017-09-29', 'valid_till': '2018-06-16', 'competition': [{'@attributes': {'ID': '1', 'title': 'easyCredit BBL Hauptrunde'}, 'spiel': [{'spiel_nummer': '0', 'bbl_spielID': '20826', 'tag': '1', 'home_id': '540', 'home': 's.Oliver Würzburg', 'homeCity': 'Würzburg', 'home_result': '76', 'gast_id': '420', 'gast': 'Brose Bamberg', 'gastCity': 'Brose Bamberg', 'gast_result': '73', 'datum': '2017-09-29', 'uhrzeit': '20:30:00', 'arenaName': 'S.Oliver-Arena', 'arenaLat': '49.77337', 'arenaLon': '9.93923', 'zuschauer': '3140', 'live_url': 'http://live.beko-bbl.de/data/bbl/540/20826.JSN', 'init_url': 'http://live.beko-bbl.de/data/bbl/540/20826.JSN'}, {'spiel_nummer': '0', 'bbl_spielID': '20827', 'tag': '1', 'home_id': '422', 'home': 'Basketball Löwen Braunschweig', 'homeCity': 'Braunschweig', 'home_result': '81', 'gast_id': '439', 'gast': 'Eisbären Bremerhaven', 'gastCity': 'Bremerhaven', 'gast_result': '68', 'datum': '2017-09-29', 'uhrzeit': '20:30:00', 

In [4]:
print(json.dumps(games, indent=4, sort_keys=True))


{
    "competition": [
        {
            "@attributes": {
                "ID": "1",
                "title": "easyCredit BBL Hauptrunde"
            },
            "spiel": [
                {
                    "arenaLat": "49.77337",
                    "arenaLon": "9.93923",
                    "arenaName": "S.Oliver-Arena",
                    "bbl_spielID": "20826",
                    "datum": "2017-09-29",
                    "gast": "Brose Bamberg",
                    "gastCity": "Brose Bamberg",
                    "gast_id": "420",
                    "gast_result": "73",
                    "home": "s.Oliver W\u00fcrzburg",
                    "homeCity": "W\u00fcrzburg",
                    "home_id": "540",
                    "home_result": "76",
                    "init_url": "http://live.beko-bbl.de/data/bbl/540/20826.JSN",
                    "live_url": "http://live.beko-bbl.de/data/bbl/540/20826.JSN",
                    "spiel_nummer": "0",
                 

In [5]:
type(games)

dict

In [6]:
import urllib.request, json 
with urllib.request.urlopen("http://statistik.easycredit-bbl.de/XML/exchange/540/Standings.php?type=json") as url:
    team = json.loads(url.read().decode())

print(team['team'][0]['team'])
print(team['team'][0]['team_id'])

FC Bayern München
486


In [7]:
t = 0
team_ids = [] 
while t < 18:
    team_ids.append(team['team'][t]['team_id'])
    t=t+1
print(team_ids)

['486', '413', '433', '420', '415', '425', '430', '426', '540', '418', '421', '422', '483', '477', '428', '439', '517', '432']


In [8]:
j = 0
team_namen = [] 
while j < 18:
    team_namen.append(team['team'][j]['team_id'])
    team_namen.append(team['team'][j]['team'])
    j=j+1

print(team_namen)

['486', 'FC Bayern München', '413', 'ALBA BERLIN', '433', 'MHP RIESEN Ludwigsburg', '420', 'Brose Bamberg', '415', 'Telekom Baskets Bonn', '425', 'medi bayreuth', '430', 'EWE Baskets Oldenburg', '426', 'FRAPORT SKYLINERS', '540', 's.Oliver Würzburg', '418', 'ratiopharm ulm', '421', 'GIESSEN 46ers', '422', 'Basketball Löwen Braunschweig', '483', 'Science City Jena', '477', 'BG Göttingen', '428', 'Mitteldeutscher BC', '439', 'Eisbären Bremerhaven', '517', 'Rockets', '432', 'WALTER Tigers Tübingen']


In [9]:
 from sklearn.preprocessing import LabelBinarizer
 encoder = LabelBinarizer()
 transformed_label = encoder.fit_transform(team_ids)

 print(transformed_label)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]]


In [10]:
home_id = "418"
index = team_ids.index(home_id)
print(index)
print(transformed_label[index])

9
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [11]:
    def make_pair(home_id, gast_id, home_win):

        home_index = team_ids.index(home_id)
        home_encoded = transformed_label[home_index]

        gast_index = team_ids.index(gast_id)
        gast_encoded = transformed_label[gast_index]

        if home_win == True:
            win_encoded = 1.0
        else: 
            win_encoded = 0.0

        return (home_encoded, gast_encoded), win_encoded

    input, output = make_pair("418", "486", False)

    print(input)
    print(output)

(array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]))
0.0


In [12]:
print (games['competition'][0]['spiel'][0]['home_id'])

540


## Preprocessing dataset: 
    - hot encoded
    - dummie variable trap

In [13]:
#
import numpy as np

def make_pair(home_id, gast_id, home_win):
        
    home_index = team_ids.index(home_id)
    home_encoded = transformed_label[home_index]

    gast_index = team_ids.index(gast_id)
    gast_encoded = transformed_label[gast_index]

    if home_win == True:
        win_encoded = 1.0
    else: win_encoded = 0.0

    return (np.append(home_encoded[0:(len(home_encoded)-1)], gast_encoded[0:(len(gast_encoded)-1)])), win_encoded
    
inputs = []
outputs = []

amount_val = 30
inputs_val = []
outputs_val = []



for i in range(0,len(games['competition'][0]['spiel'])):
    
    home_win = False

    if games['competition'][0]['spiel'][i]['home_result'] > games['competition'][0]['spiel'][i]['gast_result']:
        home_win = True
    else: home_win = False
        
    input, output = make_pair(games['competition'][0]['spiel'][i]['home_id'], games['competition'][0]['spiel'][i]['gast_id'], home_win)
    
    # Validation Menge bestimmten
    if i > 30: #len(games['competition'][0]['spiel'])-amount_val:
        inputs.append(input)
        outputs.append(output)
    else: 
        inputs_val.append(input)
        outputs_val.append(output)
        
    
    
print(inputs)
print(outputs)



[array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]), array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]), array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]), array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [14]:
# Importing the Keras libraries and packages 
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
regressor = Sequential()

# Adding the input layer and the first hidden layer
regressor.add(Dense(units = 34, kernel_initializer = 'uniform', activation = 'relu', input_shape = (34,)))

# Adding the second hidden layer
regressor.add(Dense(units = 10, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
regressor.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

#Summary 
regressor.summary()



_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 34)                1190      
_________________________________________________________________
dense_2 (Dense)              (None, 10)                350       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 11        
Total params: 1,551
Trainable params: 1,551
Non-trainable params: 0
_________________________________________________________________


In [15]:

# Compiling the ANN - wie soll es lernen
regressor.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics = ['accuracy'])

# Fitting the ANN to the Training set
history = regressor.fit(np.array(inputs), np.array(outputs), batch_size = 10, epochs = 100, validation_split = 0.1)

#history: Speichert die Lernergebniss über die Epochen


Train on 247 samples, validate on 28 samples
Epoch 1/100
247/247 [==============================] - 1s 2ms/step - loss: 0.2498 - acc: 0.5628 - val_loss: 0.2499 - val_acc: 0.5000
Epoch 2/100
247/247 [==============================] - 0s 345us/step - loss: 0.2492 - acc: 0.5628 - val_loss: 0.2497 - val_acc: 0.5000
Epoch 3/100
247/247 [==============================] - 0s 364us/step - loss: 0.2480 - acc: 0.5628 - val_loss: 0.2486 - val_acc: 0.5000
Epoch 4/100
247/247 [==============================] - 0s 254us/step - loss: 0.2446 - acc: 0.5628 - val_loss: 0.2452 - val_acc: 0.5000
Epoch 5/100
247/247 [==============================] - 0s 252us/step - loss: 0.2369 - acc: 0.5870 - val_loss: 0.2392 - val_acc: 0.6429
Epoch 6/100
247/247 [==============================] - 0s 201us/step - loss: 0.2253 - acc: 0.6397 - val_loss: 0.2320 - val_acc: 0.7143
Epoch 7/100
247/247 [==============================] - 0s 196us/step - loss: 0.2117 - acc: 0.6802 - val_loss: 0.2276 - val_acc: 0.6786
Epoch 8/100


Epoch 61/100
247/247 [==============================] - 0s 228us/step - loss: 0.0643 - acc: 0.9312 - val_loss: 0.1971 - val_acc: 0.7500
Epoch 62/100
247/247 [==============================] - 0s 248us/step - loss: 0.0609 - acc: 0.9352 - val_loss: 0.1989 - val_acc: 0.7500
Epoch 63/100
247/247 [==============================] - 0s 312us/step - loss: 0.0591 - acc: 0.9352 - val_loss: 0.1941 - val_acc: 0.7857
Epoch 64/100
247/247 [==============================] - 0s 248us/step - loss: 0.0572 - acc: 0.9393 - val_loss: 0.2009 - val_acc: 0.7143
Epoch 65/100
247/247 [==============================] - 0s 219us/step - loss: 0.0552 - acc: 0.9514 - val_loss: 0.1896 - val_acc: 0.7500
Epoch 66/100
247/247 [==============================] - 0s 210us/step - loss: 0.0526 - acc: 0.9474 - val_loss: 0.1949 - val_acc: 0.7857
Epoch 67/100
247/247 [==============================] - 0s 236us/step - loss: 0.0502 - acc: 0.9514 - val_loss: 0.1968 - val_acc: 0.7500
Epoch 68/100
247/247 [==========================

In [16]:
result = regressor.evaluate(np.array(inputs_val), np.array(outputs_val))
print(result)

31/31 [==============================] - 0s 42us/step
[0.16203585267066956, 0.774193525314331]


In [17]:
regressor.predict(np.array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,0]]))

array([[0.9817321]], dtype=float32)